[package]
name = "gluon-bug"
version = "0.1.0"
authors = ["Aashish Welling <aashishwelling@gmail.com>"]
edition = "2018"

[dependencies]
gluon = { version = "0.13.1", features = ["serialization"] }
serde_cbor = "0.10.2"
serde_state = "0.4.7"
